pipeline{
	agent { 
        	kubernetes{
            		cloud "kubernetes"
            		label "maven-build"
            		yamlFile "ibmcloud/BuildPod.yaml"
		}
    }
	parameters{
		string(defaultValue: "namespacecda", description: "Project/Namespace name", name: "project")
		string(defaultValue: "us.icr.io", description: "Registry",  name:"registry")
		string(defaultValue: "calculadora-frontend", description: "Image Name", name: "app")
		string(description: "API Address", name: "apiAddress")
	}
	stages{
		stage('Prepare'){
			steps{
				container('maven'){
					script{
						tag = sh(  script: "cd CalcExample/;  mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout", returnStdout: true )
						tag = tag.toLowerCase()
					}	
					echo "Tag: ${tag}"
				}
			}
		}
		stage('Build jar'){
			steps{
				container('maven'){
					sh "cd CalcExample/; mvn -B clean package"
				}
			}
   		}
		stage('Build Image'){
			environment {
				PATH = "/busybox:/kaniko:$PATH"
				DESTINATION = "${registry}/${project}/${app}-app:${tag}"
			}
			steps{
				container('kaniko'){
					sh  '''#!/busybox/sh
							echo "Building $DESTINATION"
							/kaniko/executor --dockerfile=Dockerfile --context="dir://`pwd`" --destination="$DESTINATION"
							'''
				}
			}
		}
		stage('Deploy'){
			environment{
				APPNAME = "${app}"
				IMAGE = "${registry}/${project}/${app}-app"
				TAG = "${tag}"
				API_ADDRESS = "${apiAddress}"
			}
			steps{
				container('helm'){
					sh 	'''#!/bin/sh
							/helm init --client-only
							/helm upgrade $APPNAME ibmcloud/charts/calculadora-app --namespace default --install --set image.repository=$IMAGE,image.tag=$TAG,apiAddress=$API_ADDRESS,ingress.enabled=true,ingress.hosts[0].host=$APPNAME.apps.ibmcloud-kubernetes.us-east.containers.appdomain.cloud,ingress.hosts[0].paths[0]=/
							'''
				}
			}
		}
	}
}